package util

/**
 * @author hanlei
 */
interface Constants {
	def error_code_mapping = [
			SUCCESS                             : '成功',
			ILLEGAL_ARGUMENT                    : '请求错误, 请稍候再试',
            ILLEGAL_PASSWORD                    : '非法密码',
			KSNNO_OR_LICENSECODE_NOT_EXIST      : '刷卡设备或激活码错误',
			SWIPER_NOT_EXIST                    : '请确认插入的是有效的刷卡器',
            KSNNO_OR_ACTIVECODE_NOT_EXIST       : '请确认刷卡器和激活码是不存在',
            KSNNO_OR_ACTIVECODE_NOT_ENABLE      : '请确认刷卡器和激活是否可用',
            KSNNO_REGISTERED                    : '刷卡器已经注册过',
            KSNNO_IS_NOT_SAME                   : '两次激活的序列号不一致',
			MOBILE_EXIST                        : '该手机已经注册, 请用其他手机号注册',
			MOBILE_NOTEXIST                     : '该手机不存在, 请用其他手机号',
            IDNUMBER_EXIST                      : '该身份证已经在该产品注册过',
            CREDIT_CARD_CANOT_REGISTER          : '信用卡不能注册',
            CARD_CANT_REGISTER                  : '该银行卡已经被注册过',
			SYSTEM_ERROR                        : '服务错误, 请稍候再试',
			KSNNO_NOT_REGISTERED                : '该设备没有被激活',
			CAN_NOT_SAVE                        : '服务错误, 请稍候再试',
			ILLEGAL_LOGIN_OR_PASSWD             : '登录名或密码错误',
			USER_LOCKED                         : '您的用户已被锁定, 请联系客服',
			USER_DISABLED                       : '您的用户不可用',
			USER_NOT_REGISTERED                 : '你的用户目前不可用',
			USER_NOT_AVAILABLE                  : '您的用户目前不可用',
			LOGIN_LOCKED                        : '您连续多次用户名密码输入错误, 稍候登录',
			WITHOUT_SESSION                     : '登录已经超时, 请重新登录',
			SESSION_TIMEOUT                     : '登录已经超时, 请重新登录',
			ILLEGAL_REQTIME                     : '请确认你的手机日期正确, 然后重新操作',
			ILLEGAL_REQNO                       : '请求错误, 如多次失败请重新登录',
			WITHOUT_PERMITS                     : '没有足够的权限操作',
			NOT_FOUND_SWIPE_OR_POS              : '您的交易用数据异常, 请联系客服解决',
			NOT_FOUND_RULE                      : '您的用户数据异常, 请联系客服解决',
			ILLEGAL_KSNNO                       : '错误的KSNNO号码, 请检查',
			ILLEGAL_AMOUNT                      : '错误的金额, 请检查后重新输入',
			NO_RESULT                           : '没有查询结果',
			IN_BLACKLIST                        : '卡交易被拒绝, 请更换其他银行卡重试',
			CARDBIN_NOT_FOUND                   : '卡片不能被受理, 可联系客服',
			FILE_EMPTY                          : '文件为空, 上传失败',
			FILE_WRITE_ERROR                    : '文件上传写入失败',
			ILLEGAL_FILENAME                    : '请上传指定类型的文件',
			ILLEGAL_FILESIZE                    : '文件太大, 请缩小尺寸重新上传',
			NOT_SELF_CARD                       : '请使用用户自己的卡付款',
			INVALID_UNIONBANKNO                 : '联行号非法, 请查证后重新输入',
			INVALID_MERCHANT                    : '商户非法, 有问题请咨询客服',
            INVALID_TERMINAL                    : '终端非法，有问题请咨询克服',
			INVALID_USERRULE                    : '用户非法, 有问题请咨询客服',
			ILLEGAL_PASSWORD                    : '密码错误, 请重新输入',
			TR_TRAN_TIME_NOT_ALLOWED            : '很抱歉, 交易被拒绝, 该时间不允许交易',
			TR_TRAN_AMOUNT_TOO_SMALL            : '很抱歉, 交易被拒绝, 交易金额过低',
			TR_TRAN_AMOUNT_TOO_MUCH             : '很抱歉, 交易被拒绝, 交易金额过高',
			TR_CARD_TIME_TOO_MUCH               : '很抱歉, 交易被拒绝, 该卡片交易次数过多',
			TR_CARD_AMOUNT_TOO_MUCH             : '很抱歉, 交易被拒绝, 该卡片交易金额过高',
			PERMISSION_DENIED                   : '抱歉, 您不能进行此操作',
			NOT_FOUND_USER                      : '错误, 请确认您的输入正确',
			ILLEGAL_BUSINESS_LICENSE            : '请输入正确的企业注册编码',
			REGISTER_LIMIT                      : '失败, 您的该公司注册的用户过多',
			ERR_TRANSLATE_PIN                   : '抱歉, 交易处理错误请确认是您匹配的刷卡器',

			NEED_POSITION                       : '此操作需要提供位置信息, 请确认您已经打开位置定位设定',

			PROCESSING                          : '交易处理中, 请稍后再试',
			SWIPE_OR_POS_NOT_MATCH              : '激活码不匹配',
            BINDING_CARD_IS_TOO_MUCH            : '绑定卡数量过多，超过8张',
            NOT_BINDING_CARD                    : '该卡没有绑定不能消费',
            INVALID_APPNAME                     : '应用名非法',
            REQUEST_TOO_OFFEN                   : '请求太频繁',
            SEND_MSG_FAILS                      : '发送短信失败',
            INVALID_IDENTIFY_CODE               : '验证码不正确',
            AFRESH_IDENTIFY                     : '请重新获取验证码',
            IDENTIFY_CODE_OVER                  : '验证码过期',
            NOT_VALIDATE                        : '该手机号没有验证',
            NOT_SETTING_FEE_RATE                : '该商户没有设置费率',
            NOT_SUPPORT_CREDIT_CARD             : '该功能不支持信用卡',
            NOT_NEW_VERSION                     : '没有新版本更新',
            QUERY_OVER_LIMIT                    : '查余超出次数限制',
            ACCOUNT_REQUIRED                    : '需要提供银行账户(卡)',
            INVALID_BANK_CARD                   : '无效银行账户(卡)',
            INVALID_FEE_TYPE                    : '该激活码不适用此设备',
            KSNNO_ACTIVATED                    : '刷卡器已经激活过',
            KSNNO_NOT_AVAILABLE                 : '请确认刷卡器是新购买的, 且没有激活过',
            KSNNO_PSAM_NOT_MATCH                : '安全卡不适用该设备',
            "00"                               :"承兑或交易成功",
            "01"                               :"查发卡行",
            "03"                               :"无效商户",
            "04"                                :"没收卡",
            "05"                                :"身份认证失败",
            "10"                                :"部分承兑",
            "11"                                :"重要人物批准（VIP）",
            "12"                                :"无效的关联交易",
            "13"                                :"无效金额",
            "14"                                :"无效卡号（无此账号）",
            "15"                                :"无此发卡方",
            "21"                                :"卡未初始化",
            "22"                                :"故障怀疑，关联交易错误",
            "25"                                :"找不到原始交易",
            "30"                                :"报文格式错误",
            "34"                                :"有作弊嫌疑",
            "38"                                :"超过允许的PIN试输入",
            "40"                                :"请求的功能尚不支持",
            "41"                                :"挂失卡",
            "43"                                :"被窃卡",
            "51"                                :"资金不足",
            "54"                                :"过期的卡",
            "55"                                :"不正确的PIN",
            "57"                                :"不允许持卡人进行的交易",
            "58"                                :"不允许终端进行的交易",
            "59"                                :"有作弊嫌疑",
            "61"                                :"超出金额限制",
            "62"                                :"受限制的卡",
            "64"                                :"原始金额错误",
            "65"                                :"超出消费次数限制",
            "68"                                :"发卡行响应超时",
            "75"                                :"允许的输入PIN次数超限",
            "90"                                :"正在日终处理",
            "91"                                :"发卡方不能操作",
            "92"                                :"中间网络无法达到",
            "94"                                :"重复交易",
            "96"                                :"系统异常、失效",
            "97"                                :"POS终端号找不到",
            "98"                                :"银联处理中心收不到发卡方应答",
            "99"                                :"PIN格式错",
            "A0"                                :"MAC鉴别失败",
            "A1"                                :"转账货币不一致",
            "A2"                                :"有缺陷的成功",
            "A3"                                :"资金到账行无此账户",
            "A4"                                :"有缺陷的成功",
            "A5"                                :"有缺陷的成功",
            "A6"                                :"有缺陷的成功",
            "A7"                                :"安全处理失败",
            "ZZ"                                :"交易失败",
            "ZA"                                :"换日强制批结",
            "D1"                                :"网络超时",
    ]

    def message_code_mapping = [
            FORGET_PASSWORD:"您正在进行忘记密码业务操作，",
            MODIFY_PHONE:"您正在进行更改手机号业务操作，",
            REGISTER:"您正在进行注册业务操作，"
    ]
    static String MPOS_MODEL = 'mpos';
    static String SHUA_MODEL = 'shua';
    static String TRANSFER_KEY = 'E086208346CBBA54A2D046866B04A745';
    static String ZERO = '0000000000000000';
}
